// src/pages/ChatPage.tsx
import React, { useEffect, useState, useRef } from 'react';
import Sidebar from '../components/layout/Sidebar';
import MessageInput from '../components/chat/MessageInput';
import { useChatContext } from '../context/ChatContext';
import { useTranslation } from 'react-i18next';
import LoadingSpinner from '../components/common/LoadingSpinner';

const ChatPage: React.FC = () => {
  const { chats, currentChatId, addMessageToChat } = useChatContext();
  const currentChat = chats.find(chat => chat.id === currentChatId);
  const [input, setInput] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false); // for mobile
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false); // for desktop
  const [showHistory, setShowHistory] = useState(false);
  const { t, i18n } = useTranslation();
  const isRTL = i18n.language === 'ar';
  const [playingMessageId, setPlayingMessageId] = useState<string | null>(null);
  const [audio, setAudio] = useState<HTMLAudioElement | null>(null);

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [currentChat?.messages]);

  // Focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Send new message
  const sendMessage = async () => {
    if (!input.trim() || !currentChatId) return;
    const userMessage = {
      id: Date.now().toString(),
      text: input.trim(),
      fromChild: true,
      timestamp: new Date().toISOString()
    };
    addMessageToChat(currentChatId, userMessage);
    setInput('');
    setIsTyping(true);
    // Simulate AI response after typing delay
    setTimeout(() => {
      const aiResponse = {
        id: (Date.now() + 1).toString(),
        text: `This is a mock AI response to: "${userMessage.text}". In a real implementation, this would be generated by the AI model.`,
        fromChild: false,
        timestamp: new Date().toISOString()
      };
      addMessageToChat(currentChatId, aiResponse);
      setIsTyping(false);
    }, 1500);
  };

  const formatTime = (timestamp?: string) => {
    if (!timestamp) return '';
    return new Date(timestamp).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // Play TTS for a message
  const playTTS = async (messageId: string, text: string) => {
    setPlayingMessageId(messageId);
    try {
      const response = await fetch('/api/tts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });
      if (!response.ok) throw new Error('Failed to fetch TTS audio');
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const audioEl = new Audio(url);
      setAudio(audioEl);
      audioEl.play();
      audioEl.onended = () => {
        setPlayingMessageId(null);
        setAudio(null);
        URL.revokeObjectURL(url);
      };
    } catch (err) {
      setPlayingMessageId(null);
      setError('Failed to play audio');
    }
  };

  // Stop audio if user navigates away
  useEffect(() => {
    return () => {
      if (audio) {
        audio.pause();
        setAudio(null);
      }
    };
  }, [audio]);

  return (
    <div className={`min-h-screen bg-white flex flex-row ${isRTL ? 'flex-row-reverse' : ''}`}>
      {/* Sidebar: fixed on desktop, overlays on mobile */}
      {/* Desktop Sidebar */}
      <aside className={`hidden md:flex flex-col h-full z-30 bg-gradient-to-b from-[#000080] to-[#000080]/90 shadow-xl fixed top-0 ${isRTL ? 'right-0' : 'left-0'} transition-all duration-300 ${sidebarCollapsed ? 'w-20' : 'w-80'}`} dir={isRTL ? 'rtl' : 'ltr'}>
        <Sidebar childId={"1"} collapsed={sidebarCollapsed} showHistory={showHistory} setShowHistory={setShowHistory} />
        {/* Collapse/Expand Button */}
        <button
          className={`absolute bottom-4 ${isRTL ? 'left-4' : 'right-4'} bg-white/20 text-white rounded-full p-2 hover:bg-white/30 transition md:block hidden`}
          onClick={() => setSidebarCollapsed(c => !c)}
          aria-label={sidebarCollapsed ? t('expandSidebar', 'Expand sidebar') : t('collapseSidebar', 'Collapse sidebar')}
        >
          {sidebarCollapsed ? (
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
          ) : (
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
          )}
        </button>
      </aside>
      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div className="fixed inset-0 z-40 flex md:hidden">
          <div className="fixed inset-0 bg-black/40" onClick={() => setSidebarOpen(false)} />
          <aside className={`relative w-64 bg-gradient-to-b from-[#000080] to-[#000080]/90 shadow-xl h-full z-50 ${isRTL ? 'right-0' : 'left-0'}`} dir={isRTL ? 'rtl' : 'ltr'}>
            <Sidebar childId={"1"} onClose={() => setSidebarOpen(false)} showHistory={showHistory} setShowHistory={setShowHistory} />
          </aside>
        </div>
      )}
      {/* Main Chat Area: offset for sidebar and appbar */}
      <main className={`flex flex-col flex-1 min-h-screen pt-[64px] pb-safe bg-gray-50 transition-all duration-300 ${sidebarCollapsed ? (isRTL ? 'md:mr-20' : 'md:ml-20') : (isRTL ? 'md:mr-80' : 'md:ml-80')}`}>
        {/* Hamburger Button for mobile */}
        <button
          className={`md:hidden fixed top-4 ${isRTL ? 'right-4' : 'left-4'} z-50 bg-[#000080] text-white rounded-full p-2 shadow-lg`}
          onClick={() => setSidebarOpen(true)}
          aria-label={t('openSidebar', 'Open sidebar')}
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>
        </button>
        {/* Error Message */}
        {error && (
           <div className="mx-4 mt-2 mb-1 p-2 bg-red-50 border border-red-200 rounded-lg animate-fadeIn text-sm max-w-screen-md mx-auto">
            <div className="flex items-center space-x-2">
                <svg className="w-4 h-4 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
              </svg>
              <span className="text-red-700">{error}</span>
            </div>
          </div>
        )}
        {/* Messages Container */}
        <div className={`flex-1 ${!currentChat ? 'flex items-center justify-center min-h-screen bg-gray-50' : 'overflow-y-auto px-2 py-2 space-y-3 bg-gray-50 max-w-screen-md w-full mx-auto'}`} style={{ minHeight: 0 }}>
          {!currentChat && (
            <div className="flex flex-col items-center justify-center space-y-4 animate-fadeIn">
              <div className="w-20 h-20 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center">
                <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
              </div>
              <div className="text-center">
                <h3 className="text-lg font-medium text-gray-800 mb-2">Welcome to AI Chat!</h3>
                <p className="text-gray-500">Start a new chat to begin your conversation</p>
              </div>
            </div>
          )}
          {currentChat && currentChat.messages.map((message, index) => (
            <div
              key={message.id}
              className={`flex ${message.fromChild ? 'justify-end' : 'justify-start'} animate-slideIn`}
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <div className={`max-w-[90vw] md:max-w-md ${message.fromChild ? 'order-2' : 'order-1'}`}>
                <div
                  className={`px-6 py-4 rounded-2xl shadow-sm message-bubble ${
                    message.fromChild
                      ? 'bg-gradient-to-r from-[#000080] to-[#000080]/90 text-white rounded-br-md'
                      : 'bg-white text-gray-800 rounded-bl-md border border-gray-100'
                  }`}
                >
                  <p className="text-sm leading-relaxed mb-1 break-words whitespace-pre-wrap">{message.text}</p>
                  {message.timestamp && (
                    <p className={`text-xs ${
                      message.fromChild ? 'text-[#000080]/80' : 'text-gray-400'
                    }`}>
                      {formatTime(message.timestamp)}
                    </p>
                  )}
                  {/* TTS Play Button for AI messages */}
                  {!message.fromChild && (
                    <button
                      className="mt-2 flex items-center space-x-2 text-[#000080] hover:text-blue-700 focus:outline-none"
                      onClick={() => playTTS(message.id, message.text)}
                      disabled={playingMessageId === message.id}
                    >
                      {playingMessageId === message.id ? (
                        <LoadingSpinner size={18} />
                      ) : (
                        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path d="M6 4l12 6-12 6V4z" /></svg>
                      )}
                      <span className="text-xs">Play</span>
                    </button>
                  )}
                </div>
              </div>
              {/* Avatar */}
              <div className={`w-10 h-10 rounded-full flex items-center justify-center mx-3 ${
                message.fromChild ? 'order-1' : 'order-2'
              }`}>
                {message.fromChild ? (
                  <div className="w-10 h-10 bg-gradient-to-r from-green-400 to-green-500 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-sm">U</span>
                  </div>
                ) : (
                  <div className="w-10 h-10 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-sm">AI</span>
                  </div>
                )}
              </div>
            </div>
          ))}
          {/* Typing Indicator */}
          {isTyping && currentChat && (
            <div className="flex justify-start animate-slideIn">
              <div className="order-2">
                <div className="px-6 py-4 bg-white text-gray-800 rounded-2xl rounded-bl-md border border-gray-100 shadow-sm">
                  <div className="flex space-x-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                  </div>
                </div>
              </div>
              <div className="w-10 h-10 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center mx-3 order-1">
                <span className="text-white font-bold text-sm">AI</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
        {/* Message Input Bar */}
        {currentChat && (
          <div className={`w-full max-w-screen-md mx-auto md:px-2 pb-safe pb-2 z-50 sticky bottom-0 bg-gray-50${showHistory ? ' opacity-50 pointer-events-none' : ''}`}>
            <MessageInput
              input={input}
              setInput={setInput}
              sendMessage={sendMessage}
              isTyping={isTyping}
              inputRef={inputRef}
            />
          </div>
        )}
      </main>
    </div>
  );
};

export default ChatPage;