// src/pages/ChatPage.tsx
import React, { useEffect, useState, useRef } from 'react';
import axiosInstance from '../api/axiosInstance';
import Sidebar from '../components/layout/Sidebar';
import { useParams } from 'react-router-dom';
import MessageInput from '../components/chat/MessageInput';
// import { useAuth } from '../context/AuthContext';

interface Message {
  id: string;
  user_input?: string;
  chatbot_response?: string;
  text: string;
  fromChild: boolean;
  timestamp?: string;
}

// Mock messages for demonstration
const MOCK_MESSAGES: Message[] = [
  {
    id: '1',
    text: 'Hello! I\'m your AI assistant. How can I help you today?',
    fromChild: false,
    timestamp: new Date(Date.now() - 300000).toISOString()
  },
  {
    id: '2',
    text: 'Hi! Can you help me with my homework?',
    fromChild: true,
    timestamp: new Date(Date.now() - 240000).toISOString()
  },
  {
    id: '3',
    text: 'Of course! I\'d be happy to help you with your homework. What subject are you working on?',
    fromChild: false,
    timestamp: new Date(Date.now() - 180000).toISOString()
  },
  {
    id: '4',
    text: 'I\'m working on math problems. Can you explain fractions?',
    fromChild: true,
    timestamp: new Date(Date.now() - 120000).toISOString()
  },
  {
    id: '5',
    text: 'Absolutely! Fractions represent parts of a whole. Think of a pizza cut into 4 equal pieces. If you eat 1 piece, you\'ve eaten 1/4 of the pizza. The top number (numerator) tells you how many parts you have, and the bottom number (denominator) tells you how many parts make up the whole.',
    fromChild: false,
    timestamp: new Date(Date.now() - 60000).toISOString()
  }
];

const ChatPage: React.FC = () => {
  const { childId } = useParams<{ childId: string }>();
  const childIdNum = Number(childId) || 1;
  // const { user } = useAuth();

  const [messages, setMessages] = useState<Message[]>(MOCK_MESSAGES);
  const [input, setInput] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Fetch and refresh chat history
  useEffect(() => {
    const fetchMessages = async () => {
      // Mock implementation for testing - no API calls
      console.log('Mock: Fetching chat history for child', childIdNum);
      // Keep using mock messages
    };

    fetchMessages();
    // No interval for testing
    // const interval = setInterval(fetchMessages, 3000);
    // return () => clearInterval(interval);
  }, [childIdNum]);

  // Send new message
  const sendMessage = async () => {
    if (!input.trim()) return;
    
    const userMessage = {
      id: Date.now().toString(),
      text: input.trim(),
      fromChild: true,
      timestamp: new Date().toISOString()
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);
    
    // Mock implementation for testing
    console.log('Mock: Sending message:', input);
      
    // Simulate AI response after typing delay
      setTimeout(() => {
      const aiResponse = {
        id: (Date.now() + 1).toString(),
        text: `This is a mock AI response to: "${input.trim()}". In a real implementation, this would be generated by the AI model.`,
        fromChild: false,
        timestamp: new Date().toISOString()
      };
      setMessages(prev => [...prev, aiResponse]);
      setIsTyping(false);
    }, 1500);
  };

  const formatTime = (timestamp?: string) => {
    if (!timestamp) return '';
    return new Date(timestamp).toLocaleTimeString([], { 
      hour: '2-digit', 
      minute: '2-digit' 
    });
  };

  return (
    <div className="min-h-screen bg-white flex flex-row">
      {/* Sidebar: fixed on desktop, overlays on mobile */}
      <aside className="hidden md:flex flex-col h-full w-80 z-30 bg-gradient-to-b from-[#000080] to-[#000080]/90 shadow-xl fixed top-0 left-0">
          <Sidebar childId={childIdNum.toString()} />
      </aside>
      {/* Main Chat Area: offset for sidebar and appbar */}
      <main className="flex flex-col flex-1 min-h-screen md:ml-80 pt-[64px] pb-safe bg-gray-50">
        {/* Error Message */}
        {error && (
           <div className="mx-4 mt-2 mb-1 p-2 bg-red-50 border border-red-200 rounded-lg animate-fadeIn text-sm max-w-screen-md mx-auto">
            <div className="flex items-center space-x-2">
                <svg className="w-4 h-4 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
              </svg>
              <span className="text-red-700">{error}</span>
            </div>
          </div>
        )}
        {/* Messages Container */}
        <div className="flex-1 overflow-y-auto px-2 py-2 space-y-3 bg-gray-50 max-w-screen-md w-full mx-auto" style={{ minHeight: 0 }}>
          {messages.length === 0 && (
            <div className="flex flex-col items-center justify-center h-full space-y-4 animate-fadeIn">
              <div className="w-20 h-20 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center">
                <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
              </div>
              <div className="text-center">
                <h3 className="text-lg font-medium text-gray-800 mb-2">Welcome to AI Chat!</h3>
                <p className="text-gray-500">Start a conversation with your AI assistant</p>
              </div>
            </div>
          )}
          {messages.map((message, index) => (
            <div
              key={message.id}
              className={`flex ${message.fromChild ? 'justify-end' : 'justify-start'} animate-slideIn`}
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <div className={`max-w-[90vw] md:max-w-md ${message.fromChild ? 'order-2' : 'order-1'}`}>
                <div
                  className={`px-6 py-4 rounded-2xl shadow-sm message-bubble ${
                    message.fromChild
                      ? 'bg-gradient-to-r from-[#000080] to-[#000080]/90 text-white rounded-br-md'
                      : 'bg-white text-gray-800 rounded-bl-md border border-gray-100'
                  }`}
                >
                  <p className="text-sm leading-relaxed mb-1 break-words whitespace-pre-wrap">{message.text}</p>
                  {message.timestamp && (
                    <p className={`text-xs ${
                      message.fromChild ? 'text-[#000080]/80' : 'text-gray-400'
                    }`}>
                      {formatTime(message.timestamp)}
                    </p>
                  )}
                </div>
              </div>
              {/* Avatar */}
              <div className={`w-10 h-10 rounded-full flex items-center justify-center mx-3 ${
                message.fromChild ? 'order-1' : 'order-2'
              }`}>
                {message.fromChild ? (
                  <div className="w-10 h-10 bg-gradient-to-r from-green-400 to-green-500 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-sm">U</span>
                  </div>
                ) : (
                  <div className="w-10 h-10 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-sm">AI</span>
                  </div>
                )}
              </div>
            </div>
          ))}
          {/* Typing Indicator */}
          {isTyping && (
            <div className="flex justify-start animate-slideIn">
              <div className="order-2">
                <div className="px-6 py-4 bg-white text-gray-800 rounded-2xl rounded-bl-md border border-gray-100 shadow-sm">
                  <div className="flex space-x-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                  </div>
                </div>
              </div>
              <div className="w-10 h-10 bg-gradient-to-r from-[#000080] to-[#000080]/90 rounded-full flex items-center justify-center mx-3 order-1">
                <span className="text-white font-bold text-sm">AI</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
        {/* Message Input Bar */}
        <div className="w-full max-w-screen-md mx-auto md:px-2 pb-safe pb-2 z-50 sticky bottom-0 bg-gray-50">
          <MessageInput
            input={input}
            setInput={setInput}
            sendMessage={sendMessage}
            isTyping={isTyping}
            inputRef={inputRef}
          />
        </div>
      </main>
    </div>
  );
};

export default ChatPage;